# package.json version change && commit message format like 'chore(release): x.y.z'
name: npm-release
on:
  push:
    branches:
      - main
jobs:
  npm-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Setup nodejs version
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Install dependencies
        run: yarn
      
      - name: Code compile and build
        run: yarn build

      - name: Run your unit test case
        run: yarn test
        
      - name: Package release
        # https://github.com/pascalgn/npm-publish-action
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          # default tag name
          tag_name: "v%s"
          # default tag message
          tag_message: "v%s"
          # create new tag
          create_tag: "true"
          # match commit message
          commit_pattern: "chore(\release\)"
          # yarn、npm or custom command
          publish_command: "yarn"
          # yarn publish has default args: --new-version、--non-interactive
          publish_args: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
